name: response_builder_example
version: 1.0.0
homepage: https://github.com/timnew/response_builder

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.25.0-beta3
  async: ^2.4.2
  response_builder:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

dependency_overrides:
  response_builder:
    path: ../
